--q1
SELECT
    O.ORDERID,
    O.ORDERDATE,
    P.PRODUCTNAME
FROM
    ORDERS O,
    PRODUCTS P,
    [ORDER DETAILS] OD
WHERE
    O.ORDERID = OD.ORDERID
    AND P.PRODUCTID = OD.PRODUCTID

 --q2
SELECT
    O.ORDERID,
    O.ORDERDATE,
    P.PRODUCTNAME,
    C.COMPANYNAME
FROM
    ORDERS O,
    PRODUCTS P,
    CUSTOMERS C,
    [ORDER DETAILS] OD
WHERE
    O.ORDERID = OD.ORDERID
    AND P.PRODUCTID = OD.PRODUCTID
    AND C.CUSTOMERID = O.CUSTOMERID

 --q3
SELECT
    O.ORDERID,
    O.ORDERDATE,
    P.PRODUCTNAME,
    CAT.CATEGORYNAME,
    C.COMPANYNAME
FROM
    ORDERS O,
    PRODUCTS P,
    CATEGORIES CAT,
    CUSTOMERS C,
    [ORDER DETAILS] OD
WHERE
    O.ORDERID = OD.ORDERID
    AND P.PRODUCTID = OD.PRODUCTID
    AND C.CUSTOMERID = O.CUSTOMERID
    AND CAT.CATEGORYID = P.CATEGORYID

 --q4
SELECT
    O.ORDERID,
    O.ORDERDATE,
    P.PRODUCTNAME
FROM
    ORDERS O,
    PRODUCTS P,
    [ORDER DETAILS] OD,
    CATEGORIES C
WHERE
    O.ORDERID = OD.ORDERID
    AND P.PRODUCTID = OD.PRODUCTID
    AND C.CATEGORYNAME = 'Seafood'
    AND C.CATEGORYID = P.CATEGORYID

 --q5
SELECT
    COUNT(*)
FROM
    ORDERS O,
    PRODUCTS P,
    [ORDER DETAILS] OD
WHERE
    O.ORDERID = '11070'
    AND P.PRODUCTID = OD.PRODUCTID

 --q6:
SELECT
    SUPPLIERS.COMPANYNAME,
    SUM(1)[NO. OF PRODUCTS SUPPLIED]
FROM
    PRODUCTS
    INNER JOIN SUPPLIERS
    ON PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID
GROUP BY
    SUPPLIERS.COMPANYNAME;

--q7:
SELECT
    SUPPLIERS.COMPANYNAME,
    CATEGORIES.CATEGORYNAME,
    COUNT(1)[NO. OF PRODUCTS SUPPLIED],
    AVG(PRODUCTS.UNITPRICE)[AVG. UNITPRICE],
    SUM(PRODUCTS.UNITSINSTOCK)[TOTAL UNITS IN STOCK]
FROM
    PRODUCTS
    INNER JOIN SUPPLIERS
    ON PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID
    INNER JOIN CATEGORIES
    ON CATEGORIES.CATEGORYID = PRODUCTS.CATEGORYID
GROUP BY
    SUPPLIERS.COMPANYNAME,
    CATEGORIES.CATEGORYNAME;

--q8:
SELECT
    SUPPLIERS.COMPANYNAME,
    COUNT(1)[NO. OF PRODUCTS SUPPLIED]
FROM
    PRODUCTS
    INNER JOIN SUPPLIERS
    ON PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID
GROUP BY
    SUPPLIERS.COMPANYNAME
HAVING
    COUNT(1) > 4;

--q9:
SELECT
    REGION,
    COUNT(1)[NO. OF EMPLOYEES]
FROM
    EMPLOYEES
GROUP BY
    REGION;

--q10:
SELECT
    SUM(UNITPRICE * QUANTITY * (1 - DISCOUNT))[TOTAL AMOUNT]
FROM
    [ORDER DETAILS]
GROUP BY
    ORDERID
HAVING
    ORDERID = 11070;

--q11:
SELECT
    ORDERID,
    SUM(UNITPRICE * QUANTITY * (1 - DISCOUNT))[TOTAL AMOUNT]
FROM
    [ORDER DETAILS]
GROUP BY
    ORDERID;

--q12:
SELECT
    CATEGORIES.CATEGORYNAME,
    COUNT(1)[NO. OF PRODUCTS]
FROM
    PRODUCTS
    INNER JOIN CATEGORIES
    ON CATEGORIES.CATEGORYID = PRODUCTS.CATEGORYID
GROUP BY
    CATEGORIES.CATEGORYNAME

 --q13:
SELECT
    CUSTOMERS.COMPANYNAME,
    SUPPLIERS.COMPANYNAME,
    COUNT(1)[NO. OF ORDERS]
FROM
    ORDERS
    INNER JOIN CUSTOMERS
    ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
    INNER JOIN [ORDER DETAILS]
    ON ORDERS.ORDERID = [ORDER DETAILS].ORDERID
    INNER JOIN PRODUCTS
    ON PRODUCTS.PRODUCTID = [ORDER DETAILS].PRODUCTID
    INNER JOIN SUPPLIERS
    ON SUPPLIERS.SUPPLIERID = PRODUCTS.SUPPLIERID
GROUP BY
    CUSTOMERS.COMPANYNAME,
    SUPPLIERS.COMPANYNAME;

--q14:
SELECT
    EMPLOYEES.FIRSTNAME +' '+ EMPLOYEES.LASTNAME [EMPLOYEE NAME],
    YEAR(ORDERS.ORDERDATE)[ORDER YEAR],
    COUNT(1)[NO. OF ORDERS]
FROM
    ORDERS
    INNER JOIN EMPLOYEES
    ON EMPLOYEES.EMPLOYEEID = ORDERS.EMPLOYEEID
GROUP BY
    EMPLOYEES.FIRSTNAME +' '+ EMPLOYEES.LASTNAME,
    YEAR(ORDERS.ORDERDATE);

--q15:
SELECT
    E.FIRSTNAME +' '+ E.LASTNAME [EMPLOYEE NAME],
    (
    SELECT
        EMPLOYEES.FIRSTNAME +' '+ EMPLOYEES.LASTNAME
    FROM
        EMPLOYEES
    WHERE
        EMPLOYEES.EMPLOYEEID = E.REPORTSTO ) [MANAGER NAME],
        COUNT(1)[NO. OF ORDERS]
    FROM
        ORDERS
        INNER JOIN EMPLOYEES E
        ON E.EMPLOYEEID = ORDERS.EMPLOYEEID
    GROUP BY
        E.FIRSTNAME +' '+ E.LASTNAME,
        E.REPORTSTO;

--q16:
SELECT
    CUSTOMERS.CUSTOMERID
FROM
    CUSTOMERS
WHERE
    CUSTOMERS.CUSTOMERID NOT IN (
        SELECT
            CUSTOMERID
        FROM
            ORDERS
    );

--q17:
SELECT
    [ORDER DETAILS].ORDERID
FROM
    [ORDER DETAILS]
    INNER JOIN PRODUCTS
    ON PRODUCTS.PRODUCTID = [ORDER DETAILS].PRODUCTID
WHERE
    PRODUCTS.CATEGORYID IN (
        SELECT
            CATEGORYID
        FROM
            CATEGORIES
        WHERE
            CATEGORYNAME IN ('Dairy products',
            'Meat/Poultry')
    )

 --q18:
SELECT
    COUNT(1) [NO. OF EMPLOYEE],
    REGION.REGIONDESCRIPTION
FROM
    EMPLOYEETERRITORIES
    INNER JOIN TERRITORIES
    ON TERRITORIES.TERRITORYID = EMPLOYEETERRITORIES.TERRITORYID
    INNER JOIN REGION
    ON REGION.REGIONID = TERRITORIES.REGIONID
GROUP BY
    REGION.REGIONDESCRIPTION

 --q19:
SELECT
    DISTINCT EMPLOYEES.FIRSTNAME+' '+EMPLOYEES.LASTNAME [EMPLOYEE NAME],
    CUSTOMERS.COMPANYNAME [CUSTOMER NAME]
FROM
    ORDERS
    CROSS JOIN EMPLOYEES
    CROSS JOIN CUSTOMERS;

--q20:
SELECT
    SHIPPERS.COMPANYNAME,
    COUNT(1)[NO. OF ORDERS FULFILLED]
FROM
    SHIPPERS
    INNER JOIN ORDERS
    ON ORDERS.SHIPVIA = SHIPPERS.SHIPPERID
GROUP BY
    SHIPPERS.COMPANYNAME